### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by georgyfarniev** [just-be-dev/vue-graphql-loader#56]
Hello. First, thanks a lot for implementing this useful module.
I have the following problem: build doesn't include *.js files when installed from npm. Can you fix it please? I find this loader pretty useful.
I duplicated this to your email. Thanks in advance.

UPD: anyway, I just want to know if this project alive and author will fix issues at best, or accept PR at worst. I would like to avoid creating fork as long as it possible.

**Comment by just-be-dev** [comment]
I'll definitely accept PRs. I haven't touched this in a bit, but I'll take a look. I need to fix the green keeper stuff anyway.

**Comment by just-be-dev** [comment]
@georgyfarniev this should be fixed in 0.3.3. Please let me know if it still doesn't work. 

I'll work on updating the build/deployment process to make it more reliable.

**Comment by georgyfarniev** [comment]
@zephraph thank you for quick response. Have you pushed changes for 0.3.3? I see only tag 0.3.2 as newest one. 

UPD: sorry, I see your 0.3.3 version pushed directly in NPM. I will try it soon and let know if something still missing. Thanks s lot!
